baseURL = 'cerbervs.github.io'
languageCode = 'en-us'
title = 'Cerbervs'
theme = "m10c"
paginate = 15
enableGitInfo = true
[params]
description = 'A collection of my poetry, copyright © 2024-present by Cerbervs'
